# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Joshua Goings 
#tagline:             ''
#description:         ''
url:                 http://joshuagoings.com
baseurl:             ''
paginate:            5
paginate_path:       "/blog/page:num"
markdown:            kramdown 
kramdown:
  parse_block_html: true
highlighter:         rouge

# Add pages here to add to header
pages_list:       
  Blog: '/blog'
#  Resume: '/assets/resume.pdf'
#  CV: '/assets/CV.pdf'
  Projects: '/projects'
  Publications: '/publications'
#  About: '/about'
#  Archive: '/archive'

# About/contact
#author:
#  name:              Joshua Goings
#  url:               https://joshuagoings.com
#  email:             

# Custom vars
#version:             1.0.0

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
