# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Joshua Goings 
#tagline:             ''
#description:         ''
url:                 http://joshuagoings.com
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"
markdown:            kramdown 

# Add pages here to add to header
pages_list:       
  CV: '/assets/CV.pdf'
#  About: '/about'
#  Archive: '/archive'

# About/contact
#author:
#  name:              Mark Otto
#  url:               https://twitter.com/mdo
#  email:             markdotto@gmail.com

# Custom vars
#version:             1.0.0
